M48
; DRILL file {KiCad 9.0.6} date 2025-12-21T07:11:06-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-21T07:11:06-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
%
G90
G05
T1
X112.338Y-98.5
T2
X134.5Y-117.0
X134.5Y-141.0
M30
